assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt

Allow assignable return types.

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt

Clarify message when multiple constructors with no assisted parameter.

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt

This also adds an ignored test for when you are performing assisted injection on a nested type. We do not generate the correct output at present.

Add some validation around private and static

---

inflation-inject-sample/src/main/java/com/example/MainActivity.java
inflation-inject-sample/src/main/java/com/example/ViewModule.java
inflation-inject/build.gradle
inflation-inject/src/main/java/com/squareup/inject/inflation/DaggerLayoutInflaterFactory.java
inflation-inject/src/main/java/com/squareup/inject/inflation/InflationInjectFactory.java
inflation-inject/src/test/java/com/squareup/inject/inflation/InflationInjectFactory2Test.kt
inflation-inject/src/test/java/com/squareup/inject/inflation/InflationInjectFactoryTest.kt

This lets you inject it without having to explicitly provide it in your graph.

Add an injectable constructor to inflater factory

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjection.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/DependencyRequest.kt
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectProcessor.kt

This matches Dagger's terminology.
Closes #30

Rename ParameterKey to DependencyRequest

---

assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2Processor.kt
assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectionModule.kt
assisted-inject-processor-dagger2/src/test/java/com/squareup/inject/assisted/processor/dagger2/AssistedInjectDagger2ProcessorTest.kt
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectProcessor.kt
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectionModule.kt
inflation-inject-processor/src/test/java/com/squareup/inject/inflation/processor/InflationInjectProcessorTest.kt

Match generated module visibility to originating module

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjection.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt

Box primitives when creating parameterized providers

---

assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2Processor.kt
assisted-inject-processor-dagger2/src/test/java/com/squareup/inject/assisted/processor/dagger2/AssistedInjectDagger2ProcessorTest.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/internal/utils.kt
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectProcessor.kt
inflation-inject-processor/src/test/java/com/squareup/inject/inflation/processor/InflationInjectProcessorTest.kt

Validate module includes contents

---

assisted-inject-processor-dagger2/src/test/java/com/squareup/inject/assisted/processor/dagger2/AssistedInjectDagger2ProcessorTest.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjection.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/internal/utils.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectionModule.kt
inflation-inject-processor/src/test/java/com/squareup/inject/inflation/processor/InflationInjectProcessorTest.kt

Support nested types

---

assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2Processor.kt
assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectionModule.kt
assisted-inject-processor-dagger2/src/test/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2ProcessorTest.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjection.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/internal/utils.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectProcessor.kt
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectionModule.kt
inflation-inject-processor/src/test/java/com/squareup/inject/inflation/processor/InflationInjectProcessorTest.kt

Add generated annotation when it is available

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt

Traverse abstract methods from supertype hierarchy

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/Key.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/NamedKey.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt

Support generics in factory parameters and return type

---

assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2Processor.kt
assisted-inject-processor-dagger2/src/test/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2ProcessorTest.kt
assisted-inject-processor-dagger2/src/test/java/com/squareup/inject/assisted/dagger2/processor/SourceGeneratingProcessor.kt

Include factories found in previous processing rounds when generating modules

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjection.kt

AssistedInjection Support Parameterized FactoryTypes

---

assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2Processor.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/internal/kotlinStdlib.kt
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectProcessor.kt

The former is already in the stdlib and the latter is a candidate. It's unlikely that a combined version will exist in the stdlib.

Switch to associate+filterNotNull

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/AssistedInjectProcessor.kt
assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt

Beef up the mismatch error message to provide more information

---

inflation-inject-processor/build.gradle
inflation-inject-processor/src/main/java/com/squareup/inject/inflation/processor/InflationInjectProcessor.kt

Add incremental annotation processing support to inflation inject

---

assisted-inject-processor/src/test/java/com/squareup/inject/assisted/processor/AssistedInjectProcessorTest.kt

Add failing test for generic parameter issue

---

assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2Processor.kt
assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectionModule.kt
assisted-inject-processor-dagger2/src/main/java/com/squareup/inject/assisted/dagger2/processor/internal/hilt.kt
assisted-inject-processor-dagger2/src/test/java/com/squareup/inject/assisted/dagger2/processor/AssistedInjectDagger2ProcessorTest.kt
assisted-inject-processor-dagger2/src/test/java/com/squareup/inject/assisted/dagger2/processor/hiltAnnotations.kt

Add @InstallIn or @DisableInstallInCheck if Hilt is used

---

assisted-inject-processor/src/main/java/com/squareup/inject/assisted/processor/Key.kt

It may not be available in the module.

Look up annotation by FQCN
